### ISSUE TITLE
Request for  'tar' Command

### ISSUE THREAD

**Issue by Rahul-Verma97** [Walchand-Linux-Users-Group/linux#56]
- tar is a fundamental tool in Linux for creating and manipulating archive files.
- Many users, particularly beginners, may not be familiar with its various options and use cases.
- Clear and well-structured documentation can improve user understanding and adoption of this important utility.

**Comment by SarojArchana** [comment]
@Rahul-Verma97  Can you please assign this issue to me

**Comment by swarraaa** [comment]
`tar` command documentation has been added.
